from .auth import auth_bp
from .users import users_bp
from .offres import offres_bp
from .demandes import demandes_bp
from .matching import matching_bp
from .conversations import conversations_bp
from .notifications import notifications_bp
from .settings import settings_bp
from .references import references_bp
